# 8081? ???? ?? ??
server:
  port: 8081

spring:
  kafka:
    # ???? Kafka ?? ??
    bootstrap-servers:
      - ${ec2_public_ip}:9092
      - ${ec2_public_ip}:19092
      - ${ec2_public_ip}:29092
    consumer:
      # ???? key ???? ?? : Kafka?? ??? ???? String?? ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ???? value ???? ?? : Kafka?? ??? ???? String?? ??
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
      # ??? ??? ?? ? ?????? ???, ??? ??? ?? ???? ???? ???? ??.
      # ?? ??? ??? ?? ???????, ?? ??? ??? ??? ????? ??.
      
      # ? ??? ?? ??? ??? ??? ?? ???? ???? ?? ?, 
      # ??? ???? ???? ?? ?? ??? ??? ??? ??? ??? ????? ?????.
      # ?? ??? ??? ???? ?? ???? ????? ???? ?? ??????.
      auto-offset-reset: earliest
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:emailDB
    driver-class-name: org.h2.Driver
    username: sa
    password: